version: "3.9"

services:
  vault:
    container_name: vault
    image: vault:1.13.3
    env_file: .env
    network_mode: host
    restart: always
    command: server
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    volumes:
      - vault:/vault/file
      - ./config.hcl:/vault/config/config.hcl
      - ./scripts/vault.init.sh:/usr/local/bin/vault.init.sh
    cap_add:
      - IPC_LOCK

volumes:
  vault:
    name: vault.data
    external: true
